-- ============================================================
-- DROP SCHEMA - SISTEMA MÉDICO - SC502
-- Ejecutar antes de correr schema.sql
-- ============================================================

USE appdb;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CITA_MEDICA_TB;
DROP TABLE IF EXISTS HORARIO_DOCTOR_TB;
DROP TABLE IF EXISTS DOCTOR_TB;
DROP TABLE IF EXISTS ESPECIALIDAD_TB;
DROP TABLE IF EXISTS TELEFONO_TB;
DROP TABLE IF EXISTS CORREO_TB;
DROP TABLE IF EXISTS USUARIO_TB;
DROP TABLE IF EXISTS TIPO_USUARIO_TB;
DROP TABLE IF EXISTS ESTADO_TB;

SET FOREIGN_KEY_CHECKS = 1;
